feat: Support building by modern OCaml (#1)
* Fix warning with deprecated module Core_kernel

The build has a number of warnings like below:

> Alert deprecated: module Core_kernel

The patch fixes warnings by renaming `Core_kernel` to `Core`.

* Fix warnings related to file_exists

The build has a number of warnings like below:

Alert deprecated: Core.Sys.file_exists
[since 2021-04] Use [Sys_unix]
File "src/moonsmith.ml", line 6, characters 5-20:
6 |   if Sys.file_exists libpath then Some(libpath)
         ^^^^^^^^^^^^^^^
Error: This expression has type [ `Use_Sys_unix ]
       This is not a function; it cannot be applied.

The patch fixes these warnings.

* Fix warnings due to using Caml

The build has warnings like below:

Alert deprecated: module Core.Caml
[since 2023-01] use Stdlib instead of Caml
File "src/ast.ml", line 243, characters 34-46:
243 |       let sorted = Caml.List.sort Caml.compare ns in
                                        ^^^^^^^^^^^^
Alert deprecated: module Core.Caml
[since 2023-01] use Stdlib instead of Caml

The patch fixes these warnings by using Stdlib instead Caml.

* Use Core.Filename.dirname