Fix warnings related to file_exists
The build has a number of warnings like below:

Alert deprecated: Core.Sys.file_exists
[since 2021-04] Use [Sys_unix]
File "src/moonsmith.ml", line 6, characters 5-20:
6 |   if Sys.file_exists libpath then Some(libpath)
         ^^^^^^^^^^^^^^^
Error: This expression has type [ `Use_Sys_unix ]
       This is not a function; it cannot be applied.

The patch fixes these warnings.